<?PHP
include('../PHP/DB.PHP');
$dato=array();
$CONSULTAR=$db->EXECUTE("SELECT s.CEDULA_RIF_SUB, s.CEDULA_RIF_USR, s.COD_CENTRO, s.COD_SOLICITUD, s.FECHA_SOLICITUD, 
								s.FECHA_VISITA, s.ID_SOLICITUD, s.MONTO_APROBADO,
						 		s.MONTO_SOLICITUD, s.OBSERVACIONES, s.OBSERVACIONES_SUBCIDIO, s.STATUS,
								 s.STATUS_INFORME, s.TRABAJADOR_SOCIAL FROM solicitud s 
						  WHERE ID_SOLICITUD='".$_GET['id']."'")or die ($db->ErrorMsg($CONSULTAR));

				
$dato['CEDULA_RIF_SUB']=$CONSULTAR->fields['CEDULA_RIF_SUB'];
$dato['CEDULA_RIF_USR']=$CONSULTAR->fields['CEDULA_RIF_USR'];
$dato['COD_CENTRO']=$CONSULTAR->fields['COD_CENTRO'];
$dato['COD_SOLICITUD']=$CONSULTAR->fields['COD_SOLICITUD'];
$dato['FECHA_VISITA']=$CONSULTAR->fields['FECHA_VISITA'];
$dato['ID_SOLICITUD']=$CONSULTAR->fields['ID_SOLICITUD'];
$dato['MONTO_APROBADO']=$CONSULTAR->fields['MONTO_APROBADO'];
$dato['MONTO_SOLICITUD']=$CONSULTAR->fields['MONTO_SOLICITUD'];
$dato['OBSERVACIONES']=$CONSULTAR->fields['OBSERVACIONES'];
$dato['OBSERVACIONES_SUBCIDIO']=$CONSULTAR->fields['OBSERVACIONES_SUBCIDIO'];
$dato['STATUS']=$CONSULTAR->fields['STATUS'];
$dato['STATUS_INFORME']=$CONSULTAR->fields['STATUS_INFORME'];
$dato['TRABAJADOR_SOCIAL']=$CONSULTAR->fields['TRABAJADOR_SOCIAL'];

echo json_encode ($dato);						  
?>