<nav>
        <div  class="menu">
        <ul>
			<li><a href="PRINCIPAL.PHP" title="Home">Inicio</a></li>
			<li><a href="LOGIN.PHP?tipo=1" title="Voluntario">Voluntario</a></li>
			<li><a href="LOGIN.PHP?tipo=2" title="Beneficiado">Beneficiado</a></li>
			<li><a href="#4" title="Conozcanos">Conozcanos</a>
            	<div class="sub-menu" style="top:36%; left:28.8%;">
                	<ul>
                    	<li><a href="MISION.PHP" title="Misión">Misión</a></li>
                        <li><a href="VISION.PHP" title="Visión">Visión</a></li>
                        <li><a href="VALORES.PHP" title="Visión">Valores</a></li>

                    </ul>
                </div>
            
            </li>
			<li><a href="CONTACTO.PHP" title="Contacto">Contacto</a></li>
			<li><a href="LEYES.php" title="Ayuda">Leyes</a></li>	
        </ul>
         <div class="recomendacion" align="center">
        Recomendamos Usar
        <br />
        <img src="../IMAGENES/Firefox.png" width="100" height="50" />
       
        </div>
       
        </div>
       
        
</nav>

                    